-- MySQL Script generated by MySQL Workbench
-- Wed Nov  1 21:40:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema artezian
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema artezian
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artezian` DEFAULT CHARACTER SET utf8 ;
USE `artezian` ;

-- -----------------------------------------------------
-- Table `artezian`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artezian`.`menu` (
  `id` INT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artezian`.`text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artezian`.`text` (
  `id` INT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `menu_id` INT(2) UNSIGNED NOT NULL,
  `text` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_text_menu1_idx` (`menu_id` ASC),
  CONSTRAINT `fk_text_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `artezian`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artezian`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artezian`.`article` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `menu_id` INT(2) UNSIGNED NOT NULL,
  `alias` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `intro` TEXT NULL,
  `content` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_article_menu1_idx` (`menu_id` ASC),
  CONSTRAINT `fk_article_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `artezian`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artezian`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artezian`.`image` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gallery_id` INT(10) UNSIGNED NOT NULL,
  `title` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_gallery1_idx` (`gallery_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_image_gallery1`
    FOREIGN KEY (`gallery_id`)
    REFERENCES `artezian`.`gallery` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artezian`.`gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artezian`.`gallery` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `image_id` INT(10) UNSIGNED NOT NULL,
  `title` VARCHAR(255) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_gallery_image1_idx` (`image_id` ASC),
  CONSTRAINT `fk_gallery_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `artezian`.`image` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
